### ISSUE TITLE
Hudbar slots

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#1]
- [x] Add some slots to the hudbar like the MFF server (tweakable in the minetest.conf)

**Comment by BetterToAutomateTheWorld** [comment]
16 slots now, simply a ingame command !

**/sethotbarsize 16**

**Comment by BetterToAutomateTheWorld** [comment]
Reopenned because it's not a solution, this setting is only for the player wich write it !

We need a feature to set 16 hot slots to every players (like in MFF)

**Comment by ObaniGemini** [comment]
On a local server it works. Someone might have changed the minetest.conf

**Comment by BetterToAutomateTheWorld** [comment]
I've onyl done an in-game command.
We need the minetest.conf set parameter.

**Comment by ObaniGemini** [comment]
https://github.com/MinetestForFun/hungry_games/commit/6c5db320d1731aa5a7cdfac00f443f347975adbe (crabman)
