### ISSUE TITLE
 /vote message

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#12]
Je remarque que beaucoup de parties ne démarrent pas uniquement car les joueurs ne font pas /vote, il y a beau avoir entre 5 et 10 joueurs, ils vagabondent à tester les jumping puzzle...

il faut rajouter une ligne de dialogue automatique toute les 30 sec(ou moins) demandant à ceux qui n'ont pas voté de le faire !

**Comment by ObaniGemini** [comment]
Si ils ne lisent pas le chat, ils ne vont pas lire les messages automatiques..............
Il faudrait leur faire un lonnnnnnng tutoriel en 126 langues pour leur apprendre comment entrer dans le chat, taper une commande,........ non merci.

Par contre, est-il possible de mettre un command bloc /vote ?

**Comment by BetterToAutomateTheWorld** [comment]
Bonn idée, un/plusieurs commandblock va/vont être mis en place

**Comment by Lymkwi** [comment]
Une fois le bloc ajouté ce ticket sera complet.

**Comment by BetterToAutomateTheWorld** [comment]
Pour le vote block : https://github.com/MinetestForFun/hungry_games/commit/583e2dea8fc68d07a92d0e6eb3a9c12911e12a26

(manque le message de "demande de vote" automatique, tous les x temps (15/30sec) si le joueur n'a pas voté)

**Comment by BetterToAutomateTheWorld** [comment]
Message if player hasn't yet voted https://github.com/MinetestForFun/hungry_games/commit/1e6ce11d36ad399aed132854a0a7204ed4183c73
