### ISSUE TITLE
Many unknow nodes

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#13]
Now we have many unknow nodes generated in chests because we deleted items/mods BUT we don't removed the loots generation from chests random generation...

**Comment by Lymkwi** [comment]
I think the last item you mentionned on irc, `default:bread_slice`, was replaced.
https://github.com/MinetestForFun/hungry_games/commit/d0fafbbc3305a4d89757f8abb45ae957af768e07

**Comment by BetterToAutomateTheWorld** [comment]
Need to check after the next merge to the server if we encounter another unknow nodes...

**Comment by ObaniGemini** [comment]
This was the only unknown node appearing. The others were blocs on the map depending on deleted mods

**Comment by BetterToAutomateTheWorld** [comment]
Ok, closed this issue because no more unknow items in chests, for the unknow item in maps, we should removed it manually
