### ISSUE TITLE
Include an automaticc pixel art of the top 1 player

### ISSUE THREAD

**Issue by ghost** [MinetestForFun/server-minetestforfun-hungry_games#14]
Make a wall of fame, for the first filing, (erase and replace if the classification changes)
1 Player ranking pixelart his name on the wall of fame.
- [x] make wall of fame on server (L 100 nodes?, H 50)
- [x] make api
- [x]  make letters/digit in table.
- [x] debug

**Comment by ObaniGemini** [comment]
https://imgrush.com/k4o9i-xWB06H

**Comment by BetterToAutomateTheWorld** [comment]
possibly improved version : print the top 3 players with a number next to the pseudo to understand which player is first, second, third !
example :

```
1. JAPP
2. Obani
3. crabman
```

**Comment by BetterToAutomateTheWorld** [comment]
For the top1 it works really great, need now a top 3 ?

the secodn an third player can be in an another color, and the top 1 with a flahsy color, maybe ?

**Comment by ghost** [comment]
Missing "TOP 3 HUNGER" on top of pixelarts  pseudo.

**Comment by BetterToAutomateTheWorld** [comment]
Now over

![top3](http://i.imgur.com/ZpsZccy.jpg)

Just need to write "Top 3" onto the players name !

**Comment by ghost** [comment]
TOP3 writed.
just a bug with pos and number of letters not centered
 ![conv-screenshot_20150818_003712](https://cloud.githubusercontent.com/assets/7189389/9318517/7010a2b2-4544-11e5-8162-bc765761e64e.jpg)
![conv-screenshot_20150818_002814](https://cloud.githubusercontent.com/assets/7189389/9318525/800c81ae-4544-11e5-81dc-de2928c3b8e1.jpg)

**Comment by BetterToAutomateTheWorld** [comment]
Not yet over because of bugs so i will keep this issue open, or it's over and i closed the issue ?

**Comment by ghost** [comment]
Fixed https://github.com/MinetestForFun/hungry_games/commit/b313c2d149fe75f589940d301bc61eec5a528e82

![conv-screenshot_20150818_121217](https://cloud.githubusercontent.com/assets/7189389/9327655/ed809aa0-45a2-11e5-9a18-fbf009a88895.jpg)

**Comment by ObaniGemini** [comment]
Nice work
