### ISSUE TITLE
Improved item_drop mod

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#16]
Take the mod from the MFF repository and import it to the MFF-HG repository, if it's possible.

**Comment by ghost** [comment]
Tu veut mettre ce truc surchargé?
ça surcharge le réseau et le proc inutilement.
avant c'était, "il est là, il est plus là", maintenant c'est "il est là, puis là, puis là, c'est bon il est plus là". :)
je crois que les joueurs s'en moquent des effets, tant qu'ils peuvent jouer confortablement.

En plus j'avais remis les bonnes var, il n'y avais plus de bug, depuis les var ont étés remplacé, les items ne tournent plus, restes sans qu'on puisses les prendre etc.
quand l'item est désactivé et réactivé le serialise ne prend pas en compte les nouvelles var --> https://github.com/MinetestForFun/minetest-minetestforfun-server/blob/master/mods/builtin_item/init.lua#L59

**Comment by BetterToAutomateTheWorld** [comment]
Mh... je réalisai pas que l'on avait autant de soucis avec ce mod sur MFF, le plus important pour moi était pas l'effet (bien qu'il soit simpa), le plus important c'était les globalsteps enlevés/réduits

**Comment by Lymkwi** [comment]
> le plus important c'était es globalsteps enlevés/réduites

Pour ce qui est juste des globalsteps, je peux m'en charger, c'est pas compliqué à faire.

**Comment by BetterToAutomateTheWorld** [comment]
Over https://github.com/MinetestForFun/hungry_games/commit/8bc085edcd41306f03a96e30bf698eafbf59e1b0
