### ISSUE TITLE
improved flowers mod

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#18]
Take the mod from MFF repository and import it to the MFF-HG repository, if it's possible.

The actual flowers mod on HG is the old mod.. MT_game use our flowers mod now...

Our code is faster.

**Comment by Lymkwi** [comment]
> Our code is faster.

Maybe not, but at least it looks cleaner, is easier to understand when you want to add a flower, and is much harder to tweak when you need to modificate just one flower.
Here we go :
https://github.com/MinetestForFun/hungry_games/commit/f2f21018362dd9a6dd35e702b4e96b5ebab5999f
