### ISSUE TITLE
improved hudbars mod

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#19]
Need to take just the "hotbar" texture from the MFF repository and add it to the MFF-HG.

The actual hotbar on MFF-HG is bugged for a 16slots hotbar.

**Comment by ghost** [comment]
fixed https://github.com/MinetestForFun/hungry_games/commit/8ee3e6398a8e26ccec83e8a41e574a64a1f769c3
