### ISSUE TITLE
Mods (or parts of mods) that shall be removed

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun-hungry_games#2]
Here is a list of the mods or parts of mods that should be removed of hungry games. Please contribute to this.
- [X] bucket : remove crafts => https://github.com/MinetestForFun/hungry_games/commit/03cb9b5a0b1e3ddefb39fa9b8c4d2a2334b7e191
- [X] doors : remove crafts => https://github.com/MinetestForFun/hungry_games/commit/03cb9b5a0b1e3ddefb39fa9b8c4d2a2334b7e191
- [X] dye : remove mod => https://github.com/MinetestForFun/hungry_games/commit/03cb9b5a0b1e3ddefb39fa9b8c4d2a2334b7e191
- [X] food : some foods aren't used => https://github.com/MinetestForFun/hungry_games/commit/b5d955ecc1a7b960af919d3385d8e42811382d1e
- [X] moreblocks : remove crafts => https://github.com/MinetestForFun/hungry_games/commit/03cb9b5a0b1e3ddefb39fa9b8c4d2a2334b7e191
- [X] vessels : switch "drinking_glass" to survival_modpack => There is already a rewrite of the drinking glass in `survival_thirst`
- [x] snow : remove sled and every thing excepeted ice, snow, snowball and weather_snow => https://github.com/MinetestForFun/hungry_games/commit/03cb9b5a0b1e3ddefb39fa9b8c4d2a2334b7e191 https://github.com/MinetestForFun/hungry_games/commit/d26e0a9067ca8c2d29ee412933f9b0b74688df17
- [X] stairs : remove crafts => https://github.com/MinetestForFun/hungry_games/commit/03cb9b5a0b1e3ddefb39fa9b8c4d2a2334b7e191
- [X] wool : remove crafts => https://github.com/MinetestForFun/hungry_games/commit/03cb9b5a0b1e3ddefb39fa9b8c4d2a2334b7e191
- [x] farming : remove mod and move bread to food mod https://github.com/MinetestForFun/hungry_games/commit/78fe8ecdfcaadfdb3415ef209800a19b0b15ac9f
- [x] carbone_mobs : every mobs excepted sheep, and every item the drop https://github.com/MinetestForFun/hungry_games/commit/192865bcc408afd204b7cf8cc800a17da702392f
- [x] stairs : remove ? (stairsplus in moreblocks) => No
- [x] survival_modpack : remove survival_hazards https://github.com/MinetestForFun/hungry_games/commit/e5b62fde4d7eeeeccff8fe716e98916e24b6f6c2

Should we remove agressive mobs ?

Do you agree with the list ?

**Comment by BetterToAutomateTheWorld** [comment]
The list is great, i think you can removed it.

Maybe we should also removed **chests** and **furnaces** ? (I've see usebug on the spawn in the HG actual server with it)
- [x] Removed chest **craft.item** only
- [X] Removed furnace **craft.item** only

**Comment by ObaniGemini** [comment]
To remove dye :
- remove textures used by maptools
- remove a craft in carbone_mobs
- remove craft system of wool

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/hungry_games/commit/03cb9b5a0b1e3ddefb39fa9b8c4d2a2334b7e191
Just clarify the precise snippets I have to remove from food, and decide what to do with mobs.
Furnaces and chests are the last one, but chests are needed by `random_chests` for random stuff around the HG arena.

**Comment by BetterToAutomateTheWorld** [comment]
See my post again, the chest and furnace mod have dependencies (of course, we missed it), we just need to removed the **craft.item** !

**Comment by ObaniGemini** [comment]
Foods that aren't used : Everything excepted : 
- food_bread_slice
- food_bun
- food_juice_apple
- food_juice_cactus

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/hungry_games/commit/b5d955ecc1a7b960af919d3385d8e42811382d1e
I removed everything edible, appart from the four items listed above and what was needed to have them.
About the chests and furnaces, do you want to :
- Make them invisible in creative inventory?
- Removed the node? (I'm sure it won't be that one)
- Remove a specific item in a mod using them? (And, in what mod and what's the itemname, please?)
- Remove the craft recipe?

**Comment by BetterToAutomateTheWorld** [comment]
Look at my post, we just need to removed the **craft recipe** ;)

**Comment by Lymkwi** [comment]
> we just need to removed the craft.item !

Well I got a bit confused.
Anyway, I looked at the code, and it seems like there are no craft recipes to make either furnaces nor chests. So, I think this is done.

**Comment by BetterToAutomateTheWorld** [comment]
Now over
