### ISSUE TITLE
Improved shields textures

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#22]
Replaced the actual shields texture (16px) with the 32px from MFF

**Comment by ghost** [comment]
fixed https://github.com/MinetestForFun/hungry_games/commit/a26c9e18b959ee79898d9aa6b95ade7e7f511310

**Comment by BetterToAutomateTheWorld** [comment]
I didn't see shields texture on this commit, great ! :)
