### ISSUE TITLE
Nodes to removed

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#23]
We can make the game lighter, jsut need to removed this nodes(i give only the description of the node, extracted from the admin inventory) :
- [x] Book https://github.com/MinetestForFun/hungry_games/commit/d17d6f5766d1ebf51799bbef086ca5f6e87193a9
- [x] clay lump https://github.com/MinetestForFun/hungry_games/commit/d17d6f5766d1ebf51799bbef086ca5f6e87193a9 (fixed by https://github.com/MinetestForFun/hungry_games/commit/3779c0f949a125288d19a57ea7327844b34c7186)
- [x] clay brick https://github.com/MinetestForFun/hungry_games/commit/d17d6f5766d1ebf51799bbef086ca5f6e87193a9 (fixed by https://github.com/MinetestForFun/hungry_games/commit/3779c0f949a125288d19a57ea7327844b34c7186)
- [x] coal lump https://github.com/MinetestForFun/hungry_games/commit/d17d6f5766d1ebf51799bbef086ca5f6e87193a9 (fixed by https://github.com/MinetestForFun/hungry_games/commit/3779c0f949a125288d19a57ea7327844b34c7186)
- [x] copper lump https://github.com/MinetestForFun/hungry_games/commit/d17d6f5766d1ebf51799bbef086ca5f6e87193a9 (fixed by https://github.com/MinetestForFun/hungry_games/commit/3779c0f949a125288d19a57ea7327844b34c7186)
- [x] furnace (only the craft) https://github.com/MinetestForFun/hungry_games/commit/d17d6f5766d1ebf51799bbef086ca5f6e87193a9
- [x] gold lump https://github.com/MinetestForFun/hungry_games/commit/d17d6f5766d1ebf51799bbef086ca5f6e87193a9 (fixed by https://github.com/MinetestForFun/hungry_games/commit/3779c0f949a125288d19a57ea7327844b34c7186)
- [x] irom lump https://github.com/MinetestForFun/hungry_games/commit/d17d6f5766d1ebf51799bbef086ca5f6e87193a9 (fixed by https://github.com/MinetestForFun/hungry_games/commit/3779c0f949a125288d19a57ea7327844b34c7186)
- [x] paper (+craft) https://github.com/MinetestForFun/hungry_games/commit/d17d6f5766d1ebf51799bbef086ca5f6e87193a9
- [x] sweeper https://github.com/MinetestForFun/hungry_games/commit/9ec1a8070c3dc337f0ccf61b011074958516c935
- [x] pine needles (snow mod) https://github.com/MinetestForFun/hungry_games/commit/b7063db94319fad91d8b85c0786f7b58778903c3
- [x] decorated pine needles (snow mod) https://github.com/MinetestForFun/hungry_games/commit/b7063db94319fad91d8b85c0786f7b58778903c3 https://github.com/MinetestForFun/hungry_games/commit/0b765d954271357d461ebcda504d4e25fae54767 
- [x] pine sapling (snow mod) https://github.com/MinetestForFun/hungry_games/commit/b18995f3f297b591c4e9f28214ccc1ed620ded10 https://github.com/MinetestForFun/hungry_games/commit/cbfb68b6a46894b249e91d4a9d5c6a6ccf5778be https://github.com/MinetestForFun/hungry_games/commit/2b03bc70fcf1b8522075d05731f3cadaa909e4f0
- [x] scorched stuff (mobs mod) https://github.com/MinetestForFun/hungry_games/commit/0101d45bd27c7f91d2000cb83eafbfe5c0c76373
- [x] cooked rat https://github.com/MinetestForFun/hungry_games/commit/0101d45bd27c7f91d2000cb83eafbfe5c0c76373
- [x] rat drop 1*apple https://github.com/MinetestForFun/hungry_games/commit/0101d45bd27c7f91d2000cb83eafbfe5c0c76373
- [x] meat https://github.com/MinetestForFun/hungry_games/commit/0101d45bd27c7f91d2000cb83eafbfe5c0c76373
- [x] raw meat https://github.com/MinetestForFun/hungry_games/commit/0101d45bd27c7f91d2000cb83eafbfe5c0c76373

**Comment by ObaniGemini** [comment]
https://github.com/MinetestForFun/hungry_games/commit/d17d6f5766d1ebf51799bbef086ca5f6e87193a9

craft was already removed for paper and furnace

**Comment by ObaniGemini** [comment]
https://github.com/MinetestForFun/hungry_games/commit/9ec1a8070c3dc337f0ccf61b011074958516c935

**Comment by BetterToAutomateTheWorld** [comment]
The minerals nodes aren't removed but they drops are replaced by  "default:cobble"

It's not a durable solution, we need to removed the placed_nodes_ and register aliases to removed old placed nodes (minerals)

**Comment by BetterToAutomateTheWorld** [comment]
The tweak for the minerals isn't necessary after reflexion, players can't dig anything :D https://github.com/MinetestForFun/hungry_games/commit/d1391a4295ccf0709cefc548d5ab062655fe538c
