### ISSUE TITLE
No more axes

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#24]
Axes are useless, do very small amount of damages, and are slow.

It's a problem because a Axe is more expensive in ressources than the equivalent sword and are very under the sword caracteristics...

So, for avoid confusing our players, we need to remove this Axes and replaced them with equivalent swords in chests :
- [x] wood axe (in chest replaced by => wood sword)
- [x] stone axe (in chest replaced by => stone sword)
- [x] steel axe (in chest replaced by => steel sword)
- [x] bronze axe (in chest replaced by => bronze sword)
- [x] mese axe (in chest replaced by => mese sword)
- [x] diamond axe (in chest replaced by => diamond sword)

**Comment by ObaniGemini** [comment]
https://github.com/MinetestForFun/hungry_games/commit/9ec1a8070c3dc337f0ccf61b011074958516c935
