### ISSUE TITLE
Many [Food] Fixs/improves

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#27]
#### Food(s) wich need to be renamed
- [x] Cactuz Juice => Cactus Juice (grammatical mistake i think) https://github.com/MinetestForFun/hungry_games/commit/84579a9be57d7b767b3793aa82a941446235c78c
#### Many foods have a really ugly textures... Need to list it and improved it (@Ataron can you do this ?) :
- [x] Bun (FR:Brioche) https://github.com/MinetestForFun/hungry_games/commit/0e603242d463f33795a6e8f3d4bb1eb4334238f7
- [x] Empty Bucket - and other buckets - (take it from MFF) https://github.com/MinetestForFun/hungry_games/commit/26db3a84288ff6bacf83b67c18b6b1318dff2258
- [x] Bread Slice (FR:Tranche de Pain) https://github.com/MinetestForFun/hungry_games/commit/d3b456fd9c5b0e1156d4f5d1739b897b09431046
- [x] Drinking Glass (empty) https://github.com/MinetestForFun/hungry_games/commit/2221b03008ce39f14b65f95e8752eba11b757f69
- [x] Glass of Water https://github.com/MinetestForFun/hungry_games/commit/2221b03008ce39f14b65f95e8752eba11b757f69
- [x] Apple Juice https://github.com/MinetestForFun/hungry_games/commit/2221b03008ce39f14b65f95e8752eba11b757f69
- [x] Cactus Juice https://github.com/MinetestForFun/hungry_games/commit/2221b03008ce39f14b65f95e8752eba11b757f69
#### Many food don't give "hungry" or "thirsty" but just life, need to change this items to restaure "hungry" or "thirsty" ! :
- [X] Apple Juice => must give thirsty => https://github.com/MinetestForFun/hungry_games/commit/7845488767cd999eeb3359663776e79571b981d0
- [X] Cactus Juice => must give thirsty => https://github.com/MinetestForFun/hungry_games/commit/7845488767cd999eeb3359663776e79571b981d0

(PS : many foods aren't in the creative inventory !)

**Comment by ghost** [comment]
fixed typo cactus https://github.com/MinetestForFun/hungry_games/commit/84579a9be57d7b767b3793aa82a941446235c78c

**Comment by Lymkwi** [comment]
> "Apple Juice => must give thirsty"
> "Cactus Juice => must give thirsty"

~~Two things could explain this bug (because `survival_thirst` actually rewrite these items to reset the thirst bar when used)~~
- ~~The callback `on_use`  is blocked by a positive answer before the execution of the rewritten `on_use` function~~
- ~~Some other mod rewrites these items' `on_use` to do something else.~~

`survival_thirst` is not rewriting the two items correctly, they are not recoded to give thirst.

EDIT: https://github.com/MinetestForFun/hungry_games/commit/7845488767cd999eeb3359663776e79571b981d0

**Comment by BetterToAutomateTheWorld** [comment]
Ok, need to check for the next merge

Thank you for your work

**Comment by BetterToAutomateTheWorld** [comment]
Done
