### ISSUE TITLE
throwing mod small improves

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#28]
Moins de "retombé" pour les flêches, il y en a trop actuellement, la portée en sera augmenter, attention a ne pas trop l'augmenter.

Si possible augmenter légèrement la vitesse des fleches aussi.

**Comment by ghost** [comment]
reduce -10 to -6 . https://github.com/MinetestForFun/hungry_games/commit/399b964e614d2f373548ff86b5f22151fb03cb7a#diff-f3f00b0a88e50a4089ad5c4b3e1de138R46

**Comment by BetterToAutomateTheWorld** [comment]
Perfect, thank you.
