### ISSUE TITLE
interact privs

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#30]
Has we think about for the voting block, every players needs to have the interact privs, so we need to grant interact to all olds players and new player,s maybe a mod wich grant the interact privilege at the connection of a player ?

**Comment by ghost** [comment]
on_join() grant interact :)

**Comment by BetterToAutomateTheWorld** [comment]
it's not enought, when a player enter in the HG arena, he gains "interact" privilege, but when he leaves the HG he losts this privilege, give interact on_join isn't enough :)

**Comment by ghost** [comment]
I think it's fixed https://github.com/MinetestForFun/hungry_games/commit/84579a9be57d7b767b3793aa82a941446235c78c

**Comment by BetterToAutomateTheWorld** [comment]
Ok, great.

But now the players in the lobby wich wait the end of the HG, have their life bar and can die in lava/acid/falling/killother players in the lobby

We need a way to re-grant the invicible stats to lobby players even if a game is already begin

**Comment by ghost** [comment]
on_die line 474 remove interact for spectate
https://github.com/MinetestForFun/hungry_games/blob/84579a9be57d7b767b3793aa82a941446235c78c/mods/hungry_games/engine.lua#L474

and line 160 stop_game regrant interact https://github.com/MinetestForFun/hungry_games/blob/84579a9be57d7b767b3793aa82a941446235c78c/mods/hungry_games/engine.lua#L160

**Comment by BetterToAutomateTheWorld** [comment]
This tweak in now over, interact an ingame privs are right :)
