### ISSUE TITLE
Spectator mod

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#31]
The spectator mod is activated but die players can't be spectator, there are jsut teleported to the lobby like the "lobby" mod and not hte "spectator" mod

**Comment by ghost** [comment]
spawn and lobby are identical, need to change position to map

> spawn 0 30000.5 0
> lobby 0 30000.5 0

**Comment by BetterToAutomateTheWorld** [comment]
Why ? 
Does the spectate mod use the spawn point ?

**Comment by BetterToAutomateTheWorld** [comment]
@crabman77 
We need to test it after the merge of yesterday so please, can you test it ?

The spectator mod/stat does it work now ?

**Comment by BetterToAutomateTheWorld** [comment]
Too many bugs with the spectator mod, and players in spectator have a skin.. can block the vision or the arrows of other players, etc... this is not a good thing..
https://github.com/MinetestForFun/hungry_games/commit/c8ad2d8dd019e4464bbea5433e35e2685b034e5c
