### ISSUE TITLE
beginning and chests

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun-hungry_games#32]
To reproduce:
- Start a new game
- during the small music, open a chest and take what you want
  You are not supposed to, the game has not started yet.
# trololo

**Comment by BetterToAutomateTheWorld** [comment]
Yes, i've alreayd tested it, i need to change the start position of players to avoid this usebug
- [x] players start position far from spawn/chests when a game begin

**Comment by BetterToAutomateTheWorld** [comment]
Over, the spawn is now different from before :

```
<Spawn number> (<max players for this spawn>) : <player numbers>
```

Spawn 1 (6 players) : 1, 4, 7, 10,  14, 18
Spawn 2 (6 players) : 2, 5, 8, 11, 15, 19
Spawn 3 (8 players) : 3, 6, 9, 12, 13, 16, 17, 20
