### ISSUE TITLE
Sruvival lib crash

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#33]
/!\ crashed the server /!\

http://zerobin.qbuissondebon.info/?e007346b5f0c1c68#uQgJ1H1Go9N3ghA+fKglMfPpxJad8T0tsp+1myhpZn4=

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/hungry_games/commit/3367e64dde59118f74e079c7799e432efa82fe6c
Should work.
