### ISSUE TITLE
Remove flowers ABM

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#34]
We need to remove the flowers abm, it's useless !

**Comment by ghost** [comment]
fixed https://github.com/MinetestForFun/hungry_games/commit/76797187e8691aa28cd54e27a2315cec0120b9c3

**Comment by BetterToAutomateTheWorld** [comment]
Done https://github.com/MinetestForFun/hungry_games/commit/76797187e8691aa28cd54e27a2315cec0120b9c3
