### ISSUE TITLE
Forum Presentation Post

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#35]
Create a forum post for the Hunger games, a simple post to present our version of this funny subgame.

With of course our website banner !

Look at the Calinou presentation for exmaple : simple and efficient.

**Comment by BetterToAutomateTheWorld** [comment]
Done => https://forum.minetest.net/viewtopic.php?f=10&t=13073#p187747

**Comment by ObaniGemini** [comment]
Nice
