### ISSUE TITLE
Small labyrinthe for the arena area

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#37]
- [x] Add a small labyrinthe to the arena

**Comment by Lymkwi** [comment]
Idealy, I think it should be made out of cobble, in an area like a desert, or somewhere on the water. It shouldn't be bigger than 20*20 and have 1 floor, with no roof.
If you have any other ideas please share them.

**Comment by ObaniGemini** [comment]
The area just under hub spawn is free. I think a big maze would be great to add there, as we can see the end and the beginning. It shall be hard because players can mark the way to the end

**Comment by Ombridride** [comment]
@ObaniGemini 
(you need to look at the new HG hub and re-read the issue ;))

**Comment by ObaniGemini** [comment]
Ok so do has you want. I don't really want to go on the server has I don't like HG's

**Comment by ObaniGemini** [comment]
I've played to much on that map on a mod I don't like just to make players come on the server

**Comment by Ombridride** [comment]
@ObaniGemini
I say re-read the topic because you don't understand the lobby already have a maze.

For information, the lobby is at y + 30 000, you can't see players in the arena.

This issue is for create a maze INTO the ARENA

**Comment by BetterToAutomateTheWorld** [comment]
Done (20*20 with 1 floor)

![laby_arena](http://i.imgur.com/nFOKjBq.jpg)

**Comment by ObaniGemini** [comment]
looks cool and pretty

**Comment by BetterToAutomateTheWorld** [comment]
Thank you, try it in-game and give us a return experience ! :p

**Comment by ObaniGemini** [comment]
Don't want to play in HG. Already tried the one in the hub and it looks nice. I think this one shall not be bad

**Comment by paly2** [comment]
Maybe it would make more high exterior walls, because we can jump over the walls without entering

**Comment by BetterToAutomateTheWorld** [comment]
i've fixed this usebug.

Now if you jump over the glasses, you can find a secret way to enter the labyrinth :)

![fixed_laby](http://i.imgur.com/b3TxxNj.jpg)
