### ISSUE TITLE
Add [irc] mod

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#4]
- [X] Add irc mod => https://github.com/MinetestForFun/hungry_games/commit/6205dad084206a23a92ef70c5ae41a6596488285
- [X] irc command mod => https://github.com/MinetestForFun/hungry_games/commit/6205dad084206a23a92ef70c5ae41a6596488285
- [x] and to the channel #minetestforfun-hg

**Comment by Lymkwi** [comment]
Should I copy the IRC mod from [MinetestForFun](https://github.com/MinetestForFun/minetest-minetestforfun-server/) or should I put it from Kaeza's repository?
About the IRC channel, I'm joining IRC right now.

**Comment by BetterToAutomateTheWorld** [comment]
Minetest.conf https://github.com/MinetestForFun/hungry_games/commit/3ad7d7506f1c8d51cbf2499050e54998e1d4d0b0

Closed because over
