### ISSUE TITLE
Textures of VOTE blocks

### ISSUE THREAD

**Issue by Ataron** [MinetestForFun/server-minetestforfun-hungry_games#40]
@ObaniGemini wanted to change VOTE's blocks textures then i propose that : 

![V](https://lut.im/MTTQ2eEz/wcW7SqSk)

but too much blue with the Sky, then I can change the background. Which color do you want ?

**Comment by Lymkwi** [comment]
(don't feel bad I tweaked the original post to show the picture directly)
It's already better than the previous "V". :+1:

**Comment by BetterToAutomateTheWorld** [comment]
Year that's great in my point of view

But maybe the blue isn't a good idea, the lobby is height in the sky so players see a background in light blue...

Anyway, it's better than the actual textures :)

**Comment by Ataron** [comment]
It don't answer :p : Which color do you want for the background block ?

**Comment by ObaniGemini** [comment]
No, I would more see a dark-grey rework of steel block for the back. For the letters, I haven't thought about it for now

**Comment by BetterToAutomateTheWorld** [comment]
For the color, i don't know sorry... The yellow was interresting because the only yellow full textured block we have in the lobby was the vote block :p

**Comment by Ataron** [comment]
I did your two ones : 
![vote v jaune](https://cloud.githubusercontent.com/assets/7973193/9418876/916e2f7c-4857-11e5-9ede-ed0084737bf9.png)
![vote v steel](https://cloud.githubusercontent.com/assets/7973193/9418883/9891951e-4857-11e5-8176-ddb0a425245a.png)

Je peux aussi facilement changer la couleur du V

**Comment by ghost** [comment]
Le jaune est flashy, ça se voit bien,sinon un petit bleu avec lettre blanche?
Une précision, le block est lumineux.
![hungry_games_blockvote_1blue](https://cloud.githubusercontent.com/assets/7189389/9419454/1873faca-485c-11e5-8407-331ade3531a0.png)

sinon une idée pour que les joueurs aient envie de le puncher, mettre des bruits(3 ou 4) drôle aléatoire quand tu n'a pas encore voté et que tu le punch.

**Comment by ObaniGemini** [comment]
@Ataron : je fais ma version et je te montre

**Comment by Ataron** [comment]
Ok

**Comment by BetterToAutomateTheWorld** [comment]
Très bonne idée les sons crabman, la plupart des joueurs étant peu agé, des petits bruits drôle serai bien ! (personnellement je verrais bien des bruit d'épées s'entrechoquant, ou d'armure ce portant, ou d'arc ce gainant, ça fait penser au combat qui approche, c'est simpa je trouve :))

Pour la luminosité des blocs, peut etre pouvons nous l'augmenter ? le serveur étant toujours en mod "jour", on ne remarque que peu la luminosité actuel

Enfin pour la couleur/texture, je pense que n'importe quel couleur serait bonne, il faut simplement que la lettre écrite soit suffisemment voyante à travers le mélange couleur bloc/couleur écriture

**Comment by Ataron** [comment]
J'ai présenté plusieurs version, attendons celle d'Obani puis tu choisiras.

**Comment by ghost** [comment]
Enfait je pensais + a des bruits du genre "pet", des truc qui les fait rire et qui leur donne envie de puncher dedans.

**Comment by BetterToAutomateTheWorld** [comment]
Err... i didn't hang the idea of "fart" when players punch a voting block, we need to create a minimum serious subgame :/

Ok @Ataron we wait for @ObaniGemini 's textures

**Comment by farfadet46** [comment]
you can make a sound by voice like "enfin !" "a voté" but if the player don't understand the french words... i think sound like medieval weapon is a good idea too :)

**Comment by ObaniGemini** [comment]
OK so I have those abstract things : 
- Top/Down (no animation)  https://imgrush.com/at3lo8Wkfi3h.png
- V : https://imgrush.com/H0p4PXMntASh.png
- O : https://imgrush.com/oXQTE5bbLXnE.png
- T : https://imgrush.com/c7Z3Xxwg77N1.png
- E : https://imgrush.com/C7tci-zaG4Yo.png

Enjoy and become epileptic !

P.S: try the Top/Down picture in-game, cause you might see some dark square on your Internet nav

**Comment by BetterToAutomateTheWorld** [comment]
The black background is a little strange for me..

BUT your work is really great, Congratulation Obani, your version seems to be ready to an in-game implementation :D

**Comment by ObaniGemini** [comment]
Yes @Ombridride , I just wanted to make minimalism, one more time :x

**Comment by BetterToAutomateTheWorld** [comment]
The animated texture is now Done

Assigned to @crabman77 the integration task

**Comment by ObaniGemini** [comment]
Ok so has the textures are awful ( I personnaly think they would be very funny lol ), I made new one with a fixed background which was made with John Smith's texture for obsidian in his 32 px texture pack : 
[Vote Blocks Album](https://imgrush.com/ae562ff67ae2)

I also added a "_Punch me_" animation to the "E" letter to notice to player they have to punch the bloc

**Comment by BetterToAutomateTheWorld** [comment]
need to try it ingame (test)

**Comment by BetterToAutomateTheWorld** [comment]
The vote blocks are now in-game, than kyo ueverybody for your work !

I thank especially @ObaniGemini for your work and textures.
