### ISSUE TITLE
Reset ranked players

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#42]
- [x] Add a reset of the ranked players table the first day of every mounth => https://github.com/MinetestForFun/hungry_games/commit/8ae6bec335ce512c6f7db2fcfb0405ed7c762c63
- [x] Add a line to explain that under the "HG ranked" board (actually empty space) => https://github.com/MinetestForFun/hungry_games/commit/630ed58f1a607e8c8aa114039d07c4d941f16dd8
- [x] Add a random_messages to explain that => https://github.com/MinetestForFun/hungry_games/commit/c7a98616e28bb95c17fa19075b8c75265ec386de

**Comment by Lymkwi** [comment]
I need to know when the Hungry Games server is supposed to restart to implement a sure system to flush the data monthly.
By that I mean, I need to know if the server will be running at midnight or during the first hour the first of every month.
EDIT: The best way to me to do that is to shutdown automatically the server before midnight every last day of the month, remove automatically the `player_ranks.txt` file, and reboot the server after midnight.

**Comment by BetterToAutomateTheWorld** [comment]
The solution is just remove the "player_ranks.txt" file before the reboot ?

If yes, i can do it in the crontab or in my reboot script.

**Comment by ghost** [comment]
heu no, remove file don't remove table in game. ranked  will rewrite file with table full.

**Comment by BetterToAutomateTheWorld** [comment]
So, what do we need ?

**Comment by ghost** [comment]
ha ok, removing file before boot.

**Comment by Lymkwi** [comment]
> heu no, remove file don't remove table in game. ranked will rewrite file with table full.

If the server is turned off, it will.
Shutting it down before midnight and restarting it after midnight is the best way to end properly every game, disconnect players, and then remove the data. Some entries in cron or a special if statement in the autoreboot script should be enough.

**Comment by BetterToAutomateTheWorld** [comment]
Shutdown the server > Removed the file > Start the server. It's must work yes.

I think a solution in the actual lua mod code will be better :
IF the server is restarting AND the date is the first day of the month (between 4h29 and 4h40 am)
THEN removed the "player_ranks.txt" file (from the world path)

**Comment by Lymkwi** [comment]
Does this look fine?
https://github.com/LeMagnesium/hungry_games/commit/0d4ebc0e8676c03c4e245822e6bd3afdc459cf39
