### ISSUE TITLE
Need to check

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#45]
Need to check the improvments of GunShip, he will commit a huge update :

https://forum.minetest.net/viewtopic.php?f=10&t=12156&view=unread#p188086

We will discuss about the "maybe" merge of his new features

**Comment by ObaniGemini** [comment]
Pourquoi ?

**Comment by Lymkwi** [comment]
So we should keep on a eye on that thread and when his repository is updated merge it into our own one? Is that what you imply?

**Comment by ObaniGemini** [comment]
No, we just need to see the new interesting thing included in future new commits. It's not about merge all repository

**Comment by BetterToAutomateTheWorld** [comment]
https://forum.minetest.net/viewtopic.php?f=50&t=13114&view=unread#p188401

**Comment by Lymkwi** [comment]
We need to merge that as soon as possible, or maybe, we should even replace our current subgame with this one, then reapply all our commits.

**Comment by BetterToAutomateTheWorld** [comment]
The merge will be a better idea because our subgame isn't very far from his subgame

**Comment by ObaniGemini** [comment]
Should we keep boats ?? With all the work we've done, I don't think a merge would be a very good idea :p We should just discuss about what should be implemented and what shouldn't. Am I right ? Or is he so far from us ?

**Comment by BetterToAutomateTheWorld** [comment]
#### A ne pas merger
- [x] 3d_armor (version que l'on a modifié et amélioration des textures)
- [x] carbone_mobs (on le garde pour l'instant)
- [x] carbone_torchs
- [x] farming (version que l'on a supprimé car fusionné dans food)
- [x] food (version que l'on a modifié, pour y incorporé farming, mais aussi pour que les liquides redonne de la soif)
- [x] sprint (ajout à nous)
- [x] Food (version que l'on a modifié)
- [x] Gauges (ajout à nous)
- [x] irc / irc_commands (ne surtout pas toucher)
- [x] mapfix (ajout à nous)
- [x] maptools (pas besoin d'update, on a une version a jour et modifié)
- [x] minesimon (ajout à nous)
- [x] name_restriction (version modifié à nous)
- [x] player_inactive (version modifié à nous)
- [x] ranks_skin (ajout à nous)
- [x] shutdown (ajout à nous)
- [x] signs_lib (ajout à nous)
- [x] sprint (ajout à nous)
- [x] throwing (le mod est à jour et on a des modifications/améliorations que cabman a fait)

#### A merger
- [x] bucket (on a rien touché)
- [x] builtin item (on a enlevé des sons inutile)
- [x] creative (on a rien touché)
- [x] default => attention aux nombreuses choses modifiés (tools supprimés/ajoutés, textures, sons - [ ] supprimés, code, etc)
- [x] craftitems (on en a viré un grand nombre pour éviter les usebug)
- [x] doors (on a rien touché)
- [x] Fire (on a viré des sons)
- [x] Flowers (on a viré les ABMs)
- [x] glass_arena (on a pas touché)
- [x] hudbars (on a pas touché)
- [x] hungry_games (on a pas mal modifié un peu de partout, faut merge mais **faire attention**)
- [x] inventory_plus (**attention** notre version est modifié avec des menus supplémentaires et adaptation pour update 3d_armor)
- [x] item_drop (on a viré des sons)
- [x] playertool (on a pas touché)
- [x] random chest (tu peux merger mais **attention** au loots des chests que l'on a modifié, dans hungry_games/engine.lua maintenant)
- [x] random_messages (on a pas touché)
- [x] spawning (on a pas touché, dans hungry_games/spawning.lua maintenant)
- [x] stairs (on a pas touché)
- [x] survival_modpack ( **attention** pas mal de choses modifié en textures, sons, chatcommand, etc => merger tout en gardant nos modifs)
- [x] wool (__attention_ on a une texture en plus, la wool_brown qu'il manquait à la base)
- [x] worldedit (on a pas touché)

#### A supprimer
- [x] snow (dans le default game maintenant)
- [x] player model (tu peux merge ou supprimé, attention car on a ajouté le modèle de LOTT, dans default/player.lua maintenant)

**Comment by BetterToAutomateTheWorld** [comment]
Started in an another issue, so closed this issue.
