### ISSUE TITLE
Add some blocks to the lobby

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#46]
Add some blocks to the lobby to avoid a 0.4.13 glitch which grant you the possibility to exit the half circle glasses made lobby...

**Comment by Lymkwi** [comment]
What is that glitch exactly? How could it make players able to get out of the lobby area?
(by the way any client hacked and recompiled can get out of the lobby just as they can avoid being hurt.. So it won't be fixable for everybody but the vast majority of our players)

**Comment by ObaniGemini** [comment]
@LeMagnesium : 0.4.13(-rc?) client allows to go threw roofs by sneaking + jumping

**Comment by BetterToAutomateTheWorld** [comment]
Fixed i think, i closed the issue.

![fix glitch 0.4.13](http://i.imgur.com/EYbVKbS.jpg)

**Comment by ObaniGemini** [comment]
Doesn't work at all

**Comment by BetterToAutomateTheWorld** [comment]
yes, don't know how to fix it without tweak the race...

**Comment by ObaniGemini** [comment]
Make a wall of two blocks high and make the roof one block higher. I will change race for it doesn't annihilate all the dificulty. Just send me a screen of the wall please for I can see what I have to modify

**Comment by BetterToAutomateTheWorld** [comment]
Fixed by @ObaniGemini, Thank you !
