### ISSUE TITLE
Tweak the lobby

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#50]
#### Tweak the lobby to be lighter
- [x] move the labyrinth far away
- [x] create 4 room for the "Simon" game of crabman

**Comment by ObaniGemini** [comment]
Why move the labyrinth far away ?
Don't we just need to put some materials on it's roof ?

**Comment by BetterToAutomateTheWorld** [comment]
BECAUSE of avoiding too many nodes into the same place, this is a **simple** way for **avoid 10FPS for slow clients**

**Comment by ObaniGemini** [comment]
Ok. And Why should we create 4 rooms for simon game ? should we not just put them the ones next to the others ?

**Comment by BetterToAutomateTheWorld** [comment]
Because of the **sounds** they emit ;)

And if it's in rooms, a little far from the lobby spawn, the chance of a player that sticks to the game nodes are reduce (if a player is sticked to the game block, you can't push it...)

**Comment by BetterToAutomateTheWorld** [comment]
Everything is done, closed the issue
