### ISSUE TITLE
improve sound, convert stereo to mono to play positional

### ISSUE THREAD

**Issue by ghost** [MinetestForFun/server-minetestforfun-hungry_games#56]
To play positional sounds, mono must be used.

http://dev.minetest.net/minetest.sound_play

> > "Only OGG files are supported. For positional playing of sounds, only single-channel (mono) files are supported. Otherwise OpenAL will play them non-positionally."

**subgame**
- [x] 3d_armor
- [x] bucket
- [x] builtin_item
- [x] carbone_mobs
- [x] carbone_torches
- [x] creative
- [x] default
- [x] doors
- [x] fire
- [x] flowers
- [x] food
- [x] gauges
- [x] glass_arena
- [x] hudbars
- [x] hungry_games
- [x] inventory_plus
- [x] irc
- [x] irc_commands
- [x] item_drop
- [x] mapfix
- [x] maptools
- [x] minesimon
- [x] moreblocks
- [x] name_restrictions
- [x] player_inactive
- [x] playermodel
- [x] playertools
- [x] random_chests
- [x] random_messages
- [x] ranks_skins
- [x] shutdown
- [x] signs_lib
- [x] snow
- [x] spawning
- [x] sprint
- [x] stairs
- [x] survival_modpack
- [x] throwing
- [x] whoison
- [x] wool
- [x] worldedit

**Comment by ghost** [comment]
Fixed 1commit https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/076fb5fc15ac1e7f9cf90b83420d8222243016a5
Fixed 2commit https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/d187ee5b7d9eb325086e8ae7bb75cc7fc220850c

before 67 éléments, total 767,4 ko
after  67 éléments, total 549,4 ko

> > 3d_armor -- 0ko --- 0ko
> > bucket -- 0ko --- 0ko
> > builtin_item -- 37,4ko --- 11,0ko
> > carbone_mobs -- 110,5ko --- 74,9ko
> > carbone_torches -- 0ko --- 0ko
> > creative -- 0ko --- 0ko
> > default -- 330,0ko --- 237,3ko
> > doors -- 0ko --- 0ko
> > fire -- 96,8ko --- 96,8ko
> > flowers -- 0ko --- 0ko
> > food -- 0ko --- 0ko
> > gauges -- 0ko --- 0ko
> > glass_arena -- 0ko --- 0ko
> > hudbars -- 0ko --- 0ko
> > hungry_games -- 121,5ko --- 101,0ko
> > inventory_plus -- 0ko --- 0ko
> > irc -- 0ko --- 0ko
> > irc_commands -- 0ko --- 0ko
> > item_drop -- 20,5ko --- 11,0ko
> > mapfix -- 0ko --- 0ko
> > maptools -- 0ko --- 0ko
> > minesimon -- 34,5ko --- 28,9ko
> > moreblocks -- 0ko --- 0ko
> > name_restrictions -- 0ko --- 0ko
> > player_inactive -- 0ko --- 0ko
> > playermodel -- 0ko --- 0ko
> > playertools -- 0ko --- 0ko
> > random_chests -- 0ko --- 0ko
> > random_messages -- 0ko --- 0ko
> > ranks_skins -- 0ko --- 0ko
> > shutdown -- 48,9ko --- 34,3ko
> > signs_lib -- 0ko --- 0ko
> > spawning -- 0ko --- 0ko
> > sprint -- 0ko --- 0ko
> > stairs -- 0ko --- 0ko
> > survival_modpack
> > survival_hunger -- 36,7ko --- 31,5ko
> > survival_ thirth-- 23,7ko --- 19,5ko
> > survival_lib -- 0ko --- 0ko
> > throwing -- 6,2ko --- 6,2ko
> > whoison -- 0ko --- 0ko
> > wool -- 0ko --- 0ko
> > worldedit -- 0ko --- 0ko

**Comment by BetterToAutomateTheWorld** [comment]
this is amazing, great job !
