### ISSUE TITLE
Ajout d'un mod

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#57]
#### Ajout du mod [itemframe] extrait de [homedecor_modpack]

C'est légé et ça permettrait d'expliquer de façon concise et illustré quelle épée est la meilleure et quelle armure est la meilleure...

Actuellement, tous les joueurs croient que la meilleure épée c'est la **bronze** ou la **mese** lol...

Ah, et ils ne lisent pas (ou très peu) les _random_messages_ expliquant quels matériaux sont les meilleurs...

**Comment by ObaniGemini** [comment]
Mese je suis d'accord mais bronze ? 0.o

**Comment by Lymkwi** [comment]
J'ai pris l'itemframes que l'on a sur MFF, si tu veux enlever des nodes dedans dis-le.
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/bc23f52a8be9453e375ebdffc80cd881158824f5

**Comment by BetterToAutomateTheWorld** [comment]
Oui, tout enlever sauf le panneau/tableau à fond blanc ;)

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/c78f89d752887ec05a09745a6b9f140e09e895bd
