### ISSUE TITLE
Website banner

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#6]
Create a slider-banner to promote the Hunger Game server in our website !

**Comment by ObaniGemini** [comment]
easy, we just need a photo from the hub and a picture from the fighting terrain. Then, a little mount with them, a good policy and let it go ^^

**Comment by BetterToAutomateTheWorld** [comment]
Obani, please can yo udo this when you have time ? :)

**Comment by BetterToAutomateTheWorld** [comment]
Over !
![hg_banner_final](http://i.imgur.com/eWQb9PV.png)

**Comment by ObaniGemini** [comment]
Change
Those
Policies
DAMN IT !

**Comment by BetterToAutomateTheWorld** [comment]
Do something better and we will change it :)

actually, i can't create something better with my Gimp skills :/

**Comment by ObaniGemini** [comment]
dafont.com
