### ISSUE TITLE
Add the 32px textures for remaining armors

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#60]
Add the 32px textures for remaining armors from summerfields modpack, don't forget do resized it properly !

Also for the MFF(origin) server !

**Comment by ObaniGemini** [comment]
the 16px one ?

**Comment by Ombridride** [comment]
Ask this kind of question on the IRC please @ObaniGemini, it's not a junk thread here :D
And your question is off topic, all of the information you need are in the issue (or in the title)... 

So, i removed your answer.

**Comment by BetterToAutomateTheWorld** [comment]
Can you do the same thing you did with MFF server ? (now for the HG)
