### ISSUE TITLE
forbidden_names.txt is not working correctly??

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun-hungry_games#61]
As you can see here, we have a player in the hunger games with the name of MrBboy45.
![capture du 2015-09-12 22 25 19](https://cloud.githubusercontent.com/assets/12512762/9833621/8332d8fc-599d-11e5-858f-13476a08ad91.png)

the bad thing is: this name is in forbidden_names.txt .
I tried with Siphano , I am not allowed to connect. this name is forbidden.
I tried with fukano and I could join
I tried with Fukano and I was dissalowed, because "this name already exists"
I tried with ZeratoR and I could join.

My personal conclusion is:
The only name that is really totally impossible to take is the first one on the list only. It could come from the server program by itself, of from an eventual mod for ban, I don't know.

I will investigate for other MFF's servers soon.

**Comment by BetterToAutomateTheWorld** [comment]
It's useless to try it on another server, this is the same mod.

Thank you for your report, we will investigate and fit it

**Comment by Lymkwi** [comment]
I can't reproduce it on localhost, I'm blocked with every blacklisted name, even when reproducing the same combination you used.

**Comment by Lymkwi** [comment]
Update: I tested everything I could on my local server, the only way it doesn't work is that forbidden_names.txt is not properly written on the server's world directory and misses a lot of names.
EDIT: **The update scripts never copied `forbidden_names.txt`, we have an old version**

**Comment by Lymkwi** [comment]
(just as a security I let this open until the next merge)

**Comment by Lymkwi** [comment]
Fixed.
