### ISSUE TITLE
Add buildings to the arena again

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#63]
#### We need to tweak a little more the arena
- [x] I think about a big building, maybe on the middle of the map, because for the moment, they haven't big buildings, just small (or maybe medium buildings) ! we can imagine a buildings with traps like cactus ground, or invisible blocks, of maybe a race/jumping puzzle, or lava falling, etc... This will be the place for challenge BUT with high reward (many chests, or maybe create a special "big chest", i don't' know)
  This big building add will be for an unic MFF-HG game experience :)
- [x] Also, i've see the cactus house, we need to add 1 or 2 additionnal chests onto it because it's a dangerous place and players loose hearth :)

**Comment by ObaniGemini** [comment]
I would really appreciate an ascension tower, with traps and races getting harder and harder.

**Comment by BetterToAutomateTheWorld** [comment]
Done.
