### ISSUE TITLE
Digged nodes in the lobby

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#64]
Some nodes (arena_glasses) in the Lobby has been digged, it's very strange, this nodes are unbreakable !

I don't know how players can do this ! Oo

**Comment by Lymkwi** [comment]
The first way for it to be possible that comes to my mind is a hacked client. Otherwise, that's impossible.

**Comment by BetterToAutomateTheWorld** [comment]
The rollback check return me nithing in 1 000 000 seconds earlier, so closed the issue... 

Surely a modified client yes...
