### ISSUE TITLE
Some little things to add

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun-hungry_games#7]
- [x] Locked signs https://github.com/MinetestForFun/hungry_games/commit/f86d9a400c6342f59da67f45dd88f81f88a40619
- [x] Players can't take stuff like admin pickaxe when dropped
- [X] Connected Glass => https://github.com/MinetestForFun/hungry_games/commit/92ae5310f2118d330b713cc719944c1f1c440a3c

**Comment by BetterToAutomateTheWorld** [comment]
- [x] Players can't take stuff like admin pickaxe when dropped => No needed because when a HG is finished, every stuffs are erased.

**Comment by BetterToAutomateTheWorld** [comment]
What's the problem with _connected glasses_ ?

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/hungry_games/commit/92ae5310f2118d330b713cc719944c1f1c440a3c
