### ISSUE TITLE
GunshipPenguin's version of HG 2.0

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#73]
Have a look at the GunshipPenguin's version of HG 2.0 and merge what we need

https://github.com/GunshipPenguin/hungry_games_plus/commits/master

**Comment by Lymkwi** [comment]
See https://github.com/MinetestForFun/server-minetestforfun-hungry_games/issues/74.

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/f6bdf13c5cb897839d101e61b5a3971692b26537
