### ISSUE TITLE
Wuzzy bug report from the forum MFF-HG thread

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#75]
From forum thread, Wuzzy says :

```
I like the idea of the “VOTE” blocks. I think something similar to that should be added to Hungry Games Plus (by GunshipPenguin).

Although I am a bit pissed off that the server has not yet merged the listrings (shift+click to instantly move items in inventory) from Hungry Games Plus. It is a very useful feature.
```
- [x] Add the Shift+click instant wear feature from Hungry Games Plus
- [x] Add a random message to inform our players about this feature https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/7d4b1a0b9901f1ee59e9735a773e09bb32a9ecdb
- [x] Our actual putted chests can't use the feature **shift+click** because they need to be removed/reputted, so we need to code something reset all of our chest formspecs => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/8fccf2878b02cc707c2ed29c191c61b6a5c4f96a

```
I just noticed that skipped games count towards the total number of “played” games and the win percentage on the ranking list.
```
- [x] Fix the "skipped" game feature, the skipped games **must** don't be counted as "played games" => (I never saw it, my commit fix any case where it might have happened) https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/c4014f1b7963d0d83a94e38af188bb7c1a81dbc0

```
Edit: Another minor thing: The red vote notification text that appears in the lobby says that the player should use the vote blocks, but in reality you must punch them. This may be confusing for newbies.
```
- [x] Fix the red sentence when players haven't already vote, use the word PUNCH VOTE BLOCK instead of USE VOTE BLOCK https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/8a551dcaaf829b37f30c7692f29b710fa88b490a

```
Edit 2: The game does not seem to start when the 2 minute voting countdown went down to 0.
```
- [x] Fix this point ^ => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/95908ec89074cca055f4bca1f0b63e7b78ead325

**Comment by Lymkwi** [comment]
~~List rings => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/pull/74~~
List rings are implemented; but the chests' formspec were not updated since they were placed before we introduced those list rings.

**Comment by Lymkwi** [comment]
Forceful game start timer : https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/95908ec89074cca055f4bca1f0b63e7b78ead325

**Comment by Lymkwi** [comment]
![](https://lut.im/B7Rgx6y5Z2/09myKfu8xm5qX273)

https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/8fccf2878b02cc707c2ed29c191c61b6a5c4f96a

**Comment by Lymkwi** [comment]
And finally
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/c4014f1b7963d0d83a94e38af188bb7c1a81dbc0

**Comment by ObaniGemini** [comment]
Epic productivity 0.o
