### ISSUE TITLE
Remove useless spikes from parcours

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun-hungry_games#76]
Some people used crafts to troll on the parcours. Can we remove them ?
- [x] Remove crafts https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/4329ac35e58f4b5c449918f2d2ff431e25bc78fd
- [x] Remove useless ones from map

**Comment by BetterToAutomateTheWorld** [comment]
Thank you for the report, and thank you for the craft recipe removal :)
We will removed the useless spikes soon

**Comment by BetterToAutomateTheWorld** [comment]
I removed all useless/putted by usebug (or our mistake to not removed the craft recipe) spikes in the black tower :)

**Comment by ObaniGemini** [comment]
Need to merge ASAP, trollers could continue to do that while it's not done.
