### ISSUE TITLE
No Bread slices in chests ?!

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#77]
I didn't see "Bread Slice" in chests since a very long time (3 or 4 months), I think this drop is just not anymore on the chests random list loots, that's not a great thing...

I done the Bread Slice texture for nothing :(

Need to re-add it to the chests loot :D !

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/5be861125e4f2c4123a953c00cb23c3e0a4edd22
