### ISSUE TITLE
Irrlicht / OpenGL error messages when joining the server

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#78]
#### Irrlicht / OpenGL error messages when joining the server

![error_when_enter_the_server](http://i.imgur.com/TcoTVW9.png)

**Comment by Lymkwi** [comment]
I don't get such errors on local nor online on the server. This is only your client.
We can't do anything for that, if you want to, report this obviously core-related issue to Minetest's repository.

**Comment by BetterToAutomateTheWorld** [comment]
I will report it when i have more time
