### ISSUE TITLE
Spectator mod (jp/kilbith version)

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#79]
#### Presentation

A simple mod allowing you to watch and continuously follow the other players in their 3rd person view.
You're invisible and undetectable for the players when you're in this mode.

Can be useful for admins or moderators in their task of monitoring.

Requires the privilege "watch".

Commands :
- /watch <player name>
- /unwatch (get back to your initial position)
#### The ideas

The idea is to add this mod and try it in local.

We want the spectator mod can be used when this conditions are true :
- [x] the player is connected and in the lobby => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/de0450ae39674cacf7b59469802792c6017eeb47
- [x] the player die in the arena and is now in the lobby => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/de0450ae39674cacf7b59469802792c6017eeb47

How to activate/call the spectator mod :
- [x] the player push a button/node on the lobby and switch to the spectator mod (like for VOTE BLOCK) => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/a6dc8c1800f3ff9388df0880a370530c2abc77d3
- [x] the player used the command /spectator or /watch, AND /unspectator or /unwatch (so, command alias or rename the command) => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/de0450ae39674cacf7b59469802792c6017eeb47
- [x] the player used a tab in its inventory (so only usable when he die and/or when he is in the lobby) => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/ae2cda8b8c42c312bdccd9ebaa384af4be3f5feb

Spectator tweaks needed for a more easy way to use it :
- [x] The spectator mod needs to be easy to use, in this purpose, add a small "previous/next/exit" formspec when a player is spectate an other player should be a great add => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/ae2cda8b8c42c312bdccd9ebaa384af4be3f5feb
- [x] the spectator mod needs to only grant the possibility to watch players in the arena (easily tweakable with the actual player privilege on the arena/lobby) => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/de0450ae39674cacf7b59469802792c6017eeb47
- [x] Maybe add a feature which grant the possibility to watched players to know how many players watch him ? => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/9a740f0df0abe0885999a388ff3fae391ce34e5f
- [x] Maybe add a feature which grant the possibility to the watcher to know the rank(if in the tab) of the player he is watching ? => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/cf22158ea5964f1735c3bd29779d51ce8869e785
- [x] Add a message when an arena player is observed, so an arena player can know when a player is observing him => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/1babc6ace923cf0e280a7ae16b05f077f88d38ba also available in the lobby
- [x] Add a message when a player enter the spectator mod to let him know he can use his inventory to control the spectator mod (maybe red message 5/10sec like when you don't vote should be good) => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/1babc6ace923cf0e280a7ae16b05f077f88d38ba used a chat message
#### Forum Link

https://forum.minetest.net/viewtopic.php?f=11&t=13718&hilit=spectator&view=unread#p201211
#### Upstream

The feature we will add should interrest @GunshipPenguin for his HG version or @kilbith for improving his spectator mod. Well, think about Upstream ! :)

**Comment by Lymkwi** [comment]
I recall there is a spectate function in Hg which we commented. However, this one allows players to choose when they want to watch.
About the places where it can be used : we can use the spawn mod's spawn names for that.
About the different means of activation : blocks, why not, aliases, meh, but the inventory : doesn't it start to be a bit bloated from all the buttons/tabs we add?
About the formspecs : This is doable thanks to the hudtoolbox I added in hungry_games, but that's also a potential source of lag.

All of this is gonna be a big pain to code for something that's already present in Hg using the fly privilege, but this enhanced version doesn't look bad at all. (just don't expect a quick merge of Hg next time)

**Comment by BetterToAutomateTheWorld** [comment]
The spectator mod actually in HG is totally bugged and not interesting at all

Command aliases because the initial command /watch /unwatch isn't really interesting, i think /spectate /unspectate should be better, maybe im wrong ? anyway an aliases for this commands isn't a problem in the HG subgame

Inventory tab because we know since a little amount of time, players in subgame wants something easy to use, and don't want to type commands (9/10 of the times)

The formspecs is a feature already added to the jp spectator mod (PR since a few days), laggy ? don't know need to test it :)

The actual spectator mod of the HG is a really pain, for many things, but, for example : a spectate player can fly between two players and the two players can't hit each other, they just hit the "spectator" which is invincible, also, the spectator player can take items in the ground (steal items of other players), they can fly out of the "glass_arena" with a little usebug and generate maps, they can also block arrows of arena players... etc... etc... this is a really BAD MOD

**Comment by Lymkwi** [comment]
I don't see any problems about players watching each other in the lobby. I've added a group of calls to `spectator.unwatching` to detach all players who are being teleported to the arena. Thus, considering that there is no bug nor problem with watching someone else in the lobby, and that disallowing it would imply adding tons of loops and calls to the engine to check privileges and spawn areas, I won't prevent any player from using `spectator` on another person who's in the lobby.
Meanwhile, I've added a (very ugly) node that, like the vote blocks, allow players to turn on spectator mode. I've also been working on a formspec usable by spectators to navigate from player to player and quit the said mode.

**Comment by BetterToAutomateTheWorld** [comment]
I create this eyes if you want them :

64px
![eye_64x64](https://cloud.githubusercontent.com/assets/8619233/12036303/fa36269c-ae44-11e5-8298-856acafe24cf.png)

32px
![eye_32x32](https://cloud.githubusercontent.com/assets/8619233/12036304/fa59a8f6-ae44-11e5-95f8-c21e5b6d8248.png)

Or you can tweak them, the eyes pixel art is great :)

For the "spectate players" feature for players in the lobby, no problem

**Comment by Lymkwi** [comment]
It's only my personal opinion but I prefer those eyes you created rather than my 16*16 poorly drawn pixel texture. Anybody else want to express their opinion about it?

**Comment by Lymkwi** [comment]
I think I'm done. If you're satisfied with the features, you can close this issue.

**Comment by BetterToAutomateTheWorld** [comment]
It seems perfect to me, really good job @LeMagnesium !

Maybe it will interest @kilbith or  @GunshipPenguin ?

Closed the issue.
