### ISSUE TITLE
Map enhancement

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun-hungry_games#8]
- [x] Fix locked chests from Calinou's server
- [x] Fix problems with griefed map, maybe make all the zone unbreakable => already done
- [x] Make some little builds in the hub ( little house, little forest,...) (Thanks to @LeMagnesium and @Ataron)
- [x] Enhance fighting map ? (Thanks to @LeMagnesium and @Ataron)
- [x] new race more difficult ? => middle race
- [x] Add 2 spawn point, and split players between these spawn point
- [x] Add a labyrinthe into the lobby/hud (30*50, 2 floors)

**Comment by BetterToAutomateTheWorld** [comment]
Can you update this issue and keep us informed about its progression ? @ObaniGemini

**Comment by BetterToAutomateTheWorld** [comment]
Done
