### ISSUE TITLE
Bulles et coeurs

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#80]
![img](http://i.imgur.com/4jO2FuZ.png)

bulles et coeurs ré-apparaissent parfois sur le HG, peut etre du au fait que je sois admin ou au fait que je sois passé en spectator ...

**Comment by Lymkwi** [comment]
If you managed to watch while playing then yes, that's because you're an admin, thus you always interact and ingame, spectator thinks you're not playing, it lets you go in spectator mode, and when you're back in playing mode it can't handle it properly.

**Comment by BetterToAutomateTheWorld** [comment]
Yes, i wonder it will be only for the admin

I closed the issue if it's the case
