### ISSUE TITLE
spectator small bugs

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#82]
- [x] when you use the random spectator button, you can random pick the player you already watch (example : p1 and p2 are ingame, p3 watch p1, p3 watch p1 and use the random button, p3 randomly re-spectate p1 ) => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/556e716d78787175115cb35b8e6ced4af2e83211
- [x] The spectated players have multiple health bar because when you spectate a player, other players in arena can see the spectate healthbar => https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/30ec9e8bd32369dfa02fac2113cb48527dcd4982

**Comment by Lymkwi** [comment]
I added ways of removing gauges and tweaked the random spectation function.
