### ISSUE TITLE
hearth bar problem

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#83]
I reported this bugs with my admin account, but we hoped it was only on admin account, so i can say no with this report...
![hearth bar problem](http://i.imgur.com/Tjj3fqa.png)

**Comment by Lymkwi** [comment]
Somehow, I still believe this shouldn't happen ; the only source possible for the bug is this :
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/75d58e813ae3663e51ea24783553861ecf12e13d

**Comment by BetterToAutomateTheWorld** [comment]
Do you think it's fixed with your latest commit ?

**Comment by BetterToAutomateTheWorld** [comment]
I closed the issue, normally it's fixed.
