### ISSUE TITLE
months of game_time (max 8)

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#84]
[game_time](http://i.imgur.com/FOnIVMr.png)

Bonne nouvelle, le **months of game_time** est resté à 3 suite au jour ou le serveur n'a pas booté correctement @gravgun 

(le script de reboot en boucle à du envoyé du curl à l'essai de lancement du serveur, je suppose)

C'est juste un ticket informatif, je le clos

**Comment by ObaniGemini** [comment]
Ça signifie que les temps de jeu n'ont pas été perdus ? Ou je comprends mal ?

**Comment by BetterToAutomateTheWorld** [comment]
Le classement du serveur est lié à un score qui est calculé selon certain critères, le critère game_time s'incrémente de 1 chaque mois et à un max de 8, il est important de le garder à 8 car même sans joueurs, ce critère fait monter le serveur dans la liste des serveurs.

Suite à la migration(canada) nous avons perdu nos scores de game_time ce qui nous à grandement descendu dans la liste des serveurs

Il y a quelques jours, un essai de script sur le HG à fait qu'il a été hors ligne 12h, le game_time ce reset si le serveur n'est pas atteignable pendant 4h, mais puisque le serveur a reboot en boucle grâce à son script de start, nous n'avons apparemment pas perdu le game_time (coup de chance)
