### ISSUE TITLE
New glass_arena mod

### ISSUE THREAD

**Issue by ObaniGemini** [MinetestForFun/server-minetestforfun-hungry_games#86]
My idea is to use the arena mod made in https://github.com/rubenwardy/capturetheflag/tree/master/mods/ctf_barrier (from _CTF_ subgame) instead of the actual one in HG.

The advantages are that it doesn't create a glass arena in the center and overrides all the world around with glass, but creates arena squares threw all the map, which allows to create **several arenas on the same map**.

It would of course require some tweaks because we need to remove the "build time" used in ctf that creates a wall between bases.
And I agree it could make it less pretty, but would permit if we create several arenas to see the other arenas from a game, and to make want to play a new match to play on the other arenas.

**Comment by BetterToAutomateTheWorld** [comment]
The actual HG system is great and didn't freeze the server like the CTF does, we can add more arenas with the actual glasses, also the HG glasses are regenerated between 2 games (if a bad people usebug to destroy some of them)

**Comment by Lymkwi** [comment]
> The advantages are that it doesn't create a glass arena in the center and overrides all the world around with glass, but creates arena squares threw all the map, which allows to create several arenas on the same map.

I actually think that is a good thing that Hg only creates one arena, as @Ombridride pointed out, map generation with CTF's version, generating on the surface of all the map, would freeze. We do not need such a mod to generate more arenas though, we can tweak the current map to accept multiple arena centers.

**Comment by ObaniGemini** [comment]
Ok I understand the point.
So maybe We should just make a 800 size arena and divide it by four, instead of one of 400 ?
I close the issue, we'll see that when the maps will be there/in building.
