### ISSUE TITLE
Kill history

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#90]
Something like this is now possible and already coded, maybe we can also add it to our HG game ?
![](https://forum.minetest.net/download/file.php?mode=view&id=5696&sid=912510ec63dc505db22dda093d6ff6aa)
https://forum.minetest.net/viewtopic.php?f=50&t=12835&view=unread#p213240

**Comment by Lymkwi** [comment]
That would be interesting on Hg indeed. It could work on Cl but I would rather not have it more overloaded than it is already.
I'll try it and add it to Hg's repo for testing.

**Comment by BetterToAutomateTheWorld** [comment]
I assigned this issue to you @LeMagnesium 
Can you inform us about your progress ?

**Comment by Lymkwi** [comment]
> Can you inform us about your progress ?

I've decided to give up on that mod you linked above, since it uses API from CTF, and I want to avoid merging too much code. I'll start coding a mod from scratch to do that.

**Comment by BetterToAutomateTheWorld** [comment]
Ok, i understand, pretty good idea

**Comment by Lymkwi** [comment]
A first version is now ready, I'll push it in the afternoon.

**Comment by ghost** [comment]
le mod crash

> 2016-05-31 11:31:55: ERROR[Main]: ServerError: Lua: Runtime error from mod 'kill_history' in callback on_dieplayer(): ..../games/minetestforfun_hg/mods/kill_history/init.lua:96: bad argument #2 to 'format' (string expected, got nil)
> 2016-05-31 11:31:55: ERROR[Main]: stack traceback:
> 2016-05-31 11:31:55: ERROR[Main]:     [C]: in function 'format'
> 2016-05-31 11:31:55: ERROR[Main]:     ..../games/minetestforfun_hg/mods/kill_history/init.lua:96: in function 'add'
> 2016-05-31 11:31:55: ERROR[Main]:     ..../games/minetestforfun_hg/mods/kill_history/init.lua:253: in function '?'

**Comment by BetterToAutomateTheWorld** [comment]
Aïe... il faut vite réparer ça !

**Comment by Lymkwi** [comment]
I removed the old junk code causing the crash, immediate merge is possible.
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/b83c8c7fbfb87f6377fc5856a9d14b85ee2bcb2a

**Comment by BetterToAutomateTheWorld** [comment]
Not yet done, but a really good beginning @LeMagnesium !
![](http://i.imgur.com/2REtAkZ.png)

**Comment by ObaniGemini** [comment]
I recommend you to use default textures :
- accident = bobblocks_majorspike ![bobblocks_majorspike.png](https://github.com/MinetestForFun/server-minetestforfun-hungry_games/blob/master/mods/bobblocks/textures/bobblocks_majorspike.png)
- burnt = fire_basic_flame.png
  ![fire_basic_flame.png](https://github.com/MinetestForFun/server-minetestforfun-hungry_games/blob/master/mods/fire/textures/fire_basic_flame.png)
- drowning = bubble ![bubble.png](https://github.com/MinetestForFun/server-minetestforfun-hungry_games/blob/master/mods/default/textures/bubble.png)
- murder = default_tool_steelsword ![default_tool_steelsword.png](https://github.com/MinetestForFun/server-minetestforfun-hungry_games/blob/master/mods/default/textures/default_tool_steelsword.png)
- starvation = default_apple ![default_apple.png](https://github.com/MinetestForFun/server-minetestforfun-hungry_games/blob/master/mods/default/textures/default_apple.png)

**Comment by Lymkwi** [comment]
> I recommend you to use defauilt textures 

Err, why not. But I would still keep my cross for hunger and drowning.

EDIT: I'll keep my icon for accidents though, bobblocks is not such a popular mod any more and I don't want to be depending on it.

**Comment by Lymkwi** [comment]
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/300fbdc186634d9d6d8491ab9472d86d6c5e389b

**Comment by BetterToAutomateTheWorld** [comment]
I agree with your choice for bobblocks

Happy to see your commits

**Comment by Lymkwi** [comment]
Is everything okay now? Can we close this?

**Comment by BetterToAutomateTheWorld** [comment]
I don't see any crash from this mod

I think everything is good, can you post a screenshot to have a preview of the the final kill history design before the closure of the issue ?

**Comment by Lymkwi** [comment]
![](https://lut.im/IDEst2UiK4/5DwwEN4VCCEQYO67)

There.

**Comment by BetterToAutomateTheWorld** [comment]
The order seems a little strange in my point of view, but if it's good for you it's good for me

**Comment by Lymkwi** [comment]
(you actually asked me to put it that way, but never mind)

**Comment by BetterToAutomateTheWorld** [comment]
No i didn't :)

I said "killer" picture "victim"
(and the picture in the "victim" direction)
