### ISSUE TITLE
Spawn and freeze

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#92]
Players aren't freeze/stuck anymore at there spawn point until the "gong", they can move anywhere, for example near a chest or run away

SINCE 0.4.14-stable

**Comment by Lymkwi** [comment]
Even with 0.4.13 stable running both server and clients, the players are not stuck at the beginning. I saw no piece of code dedicated to that so maybe it was removed. I'm going to inspect hungry_games a bit more and recode something.

**Comment by Lymkwi** [comment]
It freezes for half a second more time than it should but it works. Pushed.

**Comment by BetterToAutomateTheWorld** [comment]
Perfect, thank you
