### ISSUE TITLE
Le classement ne ce reset pas le premier du mois

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#93]
Le classement ne ce reset pas le premier du mois

**Comment by ghost** [comment]
Ce devrait être bon cette fois.

**Comment by BetterToAutomateTheWorld** [comment]
Ok, je mergerais avant la fin du mois pour le tester le 1er du mois prochain, merci pour le travail crabman

**Comment by BetterToAutomateTheWorld** [comment]
Someone can confirm me it works now ?

**Comment by Lymkwi** [comment]
We need to ask someone who is frequently on the Hungry Games server.
That or I try it locally, but I can never be sure when I try locally.

**Comment by BetterToAutomateTheWorld** [comment]
reopen this issue if not reseted ;)
