### ISSUE TITLE
Hunger

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [MinetestForFun/server-minetestforfun-hungry_games#94]
Depuis la MAJ hunger, la faim descend plus vite que la soif, hors avant c'état la soif qui descendait plus vite, il faut donc ralentir la perte de faim. 
(et il semble logique de mourir de soif avant de mourir de faim, dans la vie réel)

A voir de combien la ralentir

**Comment by Lymkwi** [comment]
Il fallait avant 2 minutes pour avoir faim, 3 minutes pour avoir soif.
Maintenant, ce seront 2 minutes pour avoir soif, et 3 minutes pour avoir faim.
https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/b8632e61d505b141708b75650420f10eab7e5e8a

**Comment by BetterToAutomateTheWorld** [comment]
Parfait, merci.
