### ISSUE TITLE
hud bar bug

### ISSUE THREAD

**Issue by Cyberpangolin** [MinetestForFun/server-minetestforfun-hungry_games#96]
discodlm57 reported this: 

![880910dplacementdebarre](https://cloud.githubusercontent.com/assets/12512762/16198085/e3a18310-3704-11e6-9664-85276240e0cf.png)

Seems to happen regularly for him, I couldn't reproduce it.

He plays in 0.4.13, maybe it can explain it.

**Comment by BetterToAutomateTheWorld** [comment]
Minetest windowed ? 
Low resolution ? 
Window square or rectangle ?

**Comment by Lymkwi** [comment]
Any news about this? I doubt it's fixable using lua code, unless it happens again.

**Comment by ghost** [comment]
fixed https://github.com/MinetestForFun/server-minetestforfun-hungry_games/commit/28db91c85edcd80e4707b9aa2af6fff278138d9c
